export const exceptionHandler = async (error: Error) => {
  //
};
